stages:
  - deploy

functions:
  stage: deploy
  image: gcr.io/triggermesh/tm:v0.0.9
  script:
    - tm -n "$KUBE_NAMESPACE" --config "$KUBECONFIG" deploy service "$CI_PROJECT_NAME" --from-image fuww/sqip-server --wait
